name: Jellyfin Server
version: 2.2.0.1
slug: jellyfinserver
description: Jellyfin Server add-on
url: https://github.com/mdvorak/ha-addon-jellyfin
webui: http://[HOST]:[PORT:8096]
arch:
  - aarch64
  - amd64
init: false
map:
  - addon_config:rw
  - share:rw
  - media:rw
  - ssl
video: true
ports:
  8096/tcp: 8096
  8920/tcp: null
ports_description:
  8096/tcp: Jellyfin web and media port
  8920/tcp: Jellyfin TLS port, must be configured in the server first
options:
  scaletail_enabled: false
  scaletail_hostname: st-jellyfin
  scaletail_auth_key: ""
  scaletail_enable_dns: false
  scaletail_dns_server: 9.9.9.9
  scaletail_accept_dns: false
schema:
  scaletail_enabled: bool
  scaletail_hostname: str
  scaletail_auth_key: password
  scaletail_enable_dns: bool
  scaletail_dns_server: str
  scaletail_accept_dns: bool
image: ghcr.io/mdvorak/jellyfin-server
